### PR TITLE
Numerous height fixes

### PR DESCRIPTION
**Pull request by sjmog**
Alters styles for short screens for:

- Holler Block
- Three up block
- Slider block
- Image grids

### CODE REVIEW

**Comment by sjmog** [comment]
Intended to resolve #20 once merged

**Comment by pitchinvasion** [comment]
Looks good.....I think

**Comment by sjmog** [comment]
+1 for visual QA: I didn't push the changes to the gh-pages repo (feels weird to merge PRs to that without QA?) so QA it locally?

I encourage everyone to use BrowserSync.

**Comment by sjmog** [comment]
Anyone else? Keen to merge this

**Pull request merged**
